spring:
  application:
    name: postsService

  datasource:
    url: jdbc:postgresql://localhost:5432/postsServiceDB
    username: postgres
    password: ganesh@123
    driver-class-name=org: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /api/v1/posts